init

diff --git a/.github/workflows/main_deploy.yml b/.github/workflows/main_deploy.yml
--- a/.github/workflows/main_deploy.yml
+++ b/.github/workflows/main_deploy.yml
@@ -83,22 +83,18 @@ jobs:
         run: |
           echo "${{ secrets.SSH_PRIVATE_KEY_PROD }}" > /tmp/ssh_key
           chmod 600 /tmp/ssh_key
-          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key ec2-user@${{ secrets.EC2_HOST_PROD }} << EOF
+          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key ec2-user@${{ secrets.EC2_HOST_PROD }} << 'EOF'
           IMAGE_TAG=${{ github.sha }}
             aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
             docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend_rds:$IMAGE_TAG
             sed -i '/backend_rds:/,/image:/s|image: .*|image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend_rds:$IMAGE_TAG|g' docker-compose.yml
              if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
-            echo "Контейнер $CONTAINER_NAME працює. Зупиняємо..."
-            
-            # Зупиняємо контейнер
-            docker compose stop $CONTAINER_NAME || echo "Не вдалося зупинити контейнер $CONTAINER_NAME"
-            
+                echo "Container $CONTAINER_NAME is running. Stopping..."
+                docker compose stop $CONTAINER_NAME || echo "Failed to stop container $CONTAINER_NAME"
+                docker compose up -d $CONTAINER_NAME || echo "Failed to start container $CONTAINER_NAME"
             else
-                echo "Контейнер $CONTAINER_NAME не запущений. Запускаємо..."
-                
-                # Запускаємо контейнер
-                docker compose up -d $CONTAINER_NAME || echo "Не вдалося запустити контейнер $CONTAINER_NAME"
+                echo "Container $CONTAINER_NAME is not running. Starting..."
+                docker compose up -d $CONTAINER_NAME || echo "Failed to start container $CONTAINER_NAME"
             fi
           EOF
           rm /tmp/ssh_key
@@ -131,8 +127,8 @@ jobs:
       - name: Build and push Docker image for backend_redis
         run: |
           IMAGE_TAG=${{ github.sha }}
-          docker build -t ${{ secrets.AWS_ECR_RDS_PROD }}:$IMAGE_TAG ./backend_redis
-          docker tag ${{ secrets.AWS_ECR_RDS_PROD }}:$IMAGE_TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend_redis:$IMAGE_TAG
+          docker build -t backend_redis:$IMAGE_TAG ./backend_redis
+          docker tag backend_redis:$IMAGE_TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend_redis:$IMAGE_TAG
           docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend_redis:$IMAGE_TAG
 
       - name: Deploy backend_redis to EC2 (main)
@@ -146,33 +142,35 @@ jobs:
         run: |
           echo "${{ secrets.SSH_PRIVATE_KEY_PROD }}" > /tmp/ssh_key
           chmod 600 /tmp/ssh_key
-          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key ec2-user@${{ secrets.EC2_HOST_PROD }} << EOF
+          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key ec2-user@${{ secrets.EC2_HOST_PROD }} << 'EOF'
             aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
             docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/backend_redis:$IMAGE_TAG
             sed -i '/backend_redis:/,/image:/s|image: .*|image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/backend_redis:$IMAGE_TAG|g' docker-compose.yml
             if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
-            echo "Контейнер $CONTAINER_NAME працює. Зупиняємо..."
-            
-            # Зупиняємо контейнер
-            docker-compose stop $CONTAINER_NAME || echo "Не вдалося зупинити контейнер $CONTAINER_NAME"
-            
+                echo "Container $CONTAINER_NAME is running. Stopping..."
+                docker compose stop $CONTAINER_NAME || echo "Failed to stop container $CONTAINER_NAME"
+                docker compose up -d $CONTAINER_NAME || echo "Failed to start container $CONTAINER_NAME"
             else
-                echo "Контейнер $CONTAINER_NAME не запущений. Запускаємо..."
-                
-                # Запускаємо контейнер
-                docker-compose up -d $CONTAINER_NAME || echo "Не вдалося запустити контейнер $CONTAINER_NAME"
+                echo "Container $CONTAINER_NAME is not running. Starting..."
+                docker compose up -d $CONTAINER_NAME || echo "Failed to start container $CONTAINER_NAME"
             fi
           EOF
           rm /tmp/ssh_key
 
-
-  deploy_frontend_to_s3_main:
+  deploy_frontend_main:
     runs-on: ubuntu-latest
     needs: check_folder_changes
     if: needs.check_folder_changes.outputs.frontend_changed == 'true' && github.ref == 'refs/heads/main'
+    
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
+
+      - name: Install SSH Key
+        uses: shimataro/ssh-key-action@v2
+        with:
+          key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
+          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v2
@@ -184,11 +182,11 @@ jobs:
       - name: Log in to Amazon ECR
         run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
 
-      - name: Build and push Docker image for backend_redis
+      - name: Build and push Docker image for frontend
         run: |
           IMAGE_TAG=${{ github.sha }}
-          docker build -t ${{ secrets.AWS_ECR_RDS_PROD }}:$IMAGE_TAG ./frontend
-          docker tag ${{ secrets.AWS_ECR_RDS_PROD }}:$IMAGE_TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/frontend:$IMAGE_TAG
+          docker build -t frontend:$IMAGE_TAG ./frontend
+          docker tag frontend:$IMAGE_TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/frontend:$IMAGE_TAG
           docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/frontend:$IMAGE_TAG
 
       - name: Deploy frontend to EC2 (main)
@@ -202,21 +200,17 @@ jobs:
         run: |
           echo "${{ secrets.SSH_PRIVATE_KEY_PROD }}" > /tmp/ssh_key
           chmod 600 /tmp/ssh_key
-          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key ec2-user@${{ secrets.EC2_HOST_PROD }} << EOF
+          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key ec2-user@${{ secrets.EC2_HOST_PROD }} << 'EOF'
             aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
             docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:$IMAGE_TAG
             sed -i '/frontend:/,/image:/s|image: .*|image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:$IMAGE_TAG|g' docker-compose.yml
             if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
-            echo "Контейнер $CONTAINER_NAME працює. Зупиняємо..."
-            
-            # Зупиняємо контейнер
-            docker compose stop $CONTAINER_NAME || echo "Не вдалося зупинити контейнер $CONTAINER_NAME"
-            
+                echo "Container $CONTAINER_NAME is running. Stopping..."
+                docker compose stop $CONTAINER_NAME || echo "Failed to stop container $CONTAINER_NAME"
+                docker compose up -d $CONTAINER_NAME || echo "Failed to start container $CONTAINER_NAME"
             else
-                echo "Контейнер $CONTAINER_NAME не запущений. Запускаємо..."
-                
-                # Запускаємо контейнер
-                docker compose up -d $CONTAINER_NAME || echo "Не вдалося запустити контейнер $CONTAINER_NAME"
+                echo "Container $CONTAINER_NAME is not running. Starting..."
+                docker compose up -d $CONTAINER_NAME || echo "Failed to start container $CONTAINER_NAME"
             fi
           EOF
           rm /tmp/ssh_key
